extends Node

@export var ITEM_HANDLER: Node
@export var BOARD_TILEMAP: TileMap
@export var ITEM_TILEMAP: TileMap
@export var PARTICLES: GPUParticles2D
@export var PLAYER: CharacterBody2D

@export var TIMER_PROGRESS_BAR: ProgressBar
@export var TIMER_LABEL: Label
@export var INSTANT_EFFECT_LABEL: Label
@export var EFFECT_LABEL: Label
@export var SCORE_TIME_LABEL: Label

@export var DARKNESS_OVERLAY: ColorRect
@export var SOUND_EFFECT_HANDLER: AudioStreamPlayer
@export var GAME_OVER_CONTAINER: Control
@export var GAME_OVER_STAT_LABEL: Label

@export var DIE_SOUND_EFFECT: AudioStream
@export var PICKUP_SOUND_EFFECT: AudioStream

func _ready():
	Global.ITEM_HANDLER = ITEM_HANDLER
	Global.BOARD_TILEMAP = BOARD_TILEMAP
	Global.ITEM_TILEMAP = ITEM_TILEMAP
	Global.PARTICLES = PARTICLES
	Global.PLAYER = PLAYER
	Global.TIMER_PROGRESS_BAR = TIMER_PROGRESS_BAR
	Global.TIMER_LABEL = TIMER_LABEL
	Global.INSTANT_EFFECT_LABEL = INSTANT_EFFECT_LABEL
	Global.EFFECT_LABEL = EFFECT_LABEL
	Global.SCORE_TIME_LABEL = SCORE_TIME_LABEL
	Global.DARKNESS_OVERLAY = DARKNESS_OVERLAY
	Global.SOUND_EFFECT_HANDLER = SOUND_EFFECT_HANDLER
	Global.GAME_OVER_CONTAINER = GAME_OVER_CONTAINER
	Global.GAME_OVER_STAT_LABEL = GAME_OVER_STAT_LABEL
	Global.DIE_SOUND_EFFECT = DIE_SOUND_EFFECT
	Global.PICKUP_SOUND_EFFECT = PICKUP_SOUND_EFFECT
